version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    build:
      context: ./docker/mysql
    container_name: hrdirector-db
    env_file: [laravel/.env.example]
    working_dir: /workspace
    ports:
      - "4306:3306"
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ./data:/var/lib/mysql
      - ./docker/mysql/hrdirector.cnf:/etc/mysql/conf.d/hrdirector.cnf
      - ./docker/db/import.sh:/workspace/import.sh
      - ./config:/workspace/config
      - ./Capfile:/workspace/Capfile
      - ./laravel/.env.example:/workspace/laravel/.env
      - ./database:/workspace/database
  php:
    build:
      context: ./docker/php
    container_name: hrdirector-php
    working_dir: /code/laravel
    volumes:
      - ./httpdocs:/code/httpdocs
      - ./laravel:/code/laravel
      - ./laravel/.env.example:/code/.env
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    depends_on:
      - db
    env_file: [laravel/.env.example]
    environment:
      PHP_IDE_CONFIG: serverName=PHPSERVERDOCKER
  web:
    image: nginx:latest
    container_name: hrdirector-web
    depends_on:
      - php
    volumes:
      - ./httpdocs:/code/httpdocs
      - ./laravel:/code/laravel
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx-selfsigned-hrdirector.key:/etc/nginx/conf.d/nginx-selfsigned-hrdirector.key
      - ./docker/nginx/nginx-selfsigned-hrdirector.crt:/etc/nginx/conf.d/nginx-selfsigned-hrdirector.crt
    ports:
      - "80:80"
      - "443:443"
  node:
    build:
      context: ./docker/node
    container_name: hrdirector-node
    user: "node"
    ports:
      - "8089:8089"
      - "1080:1080"
      - "1025:1025"
    working_dir: /home/node/app
    command: "./run.sh"
    environment:
      - NODE_ENV=development
    volumes:
      - ./httpdocs:/home/node/httpdocs
      - ./laravel:/home/node/app
      - ./docker/node/run.sh:/home/node/app/run.sh
      - ./docker/node/setup.sh:/home/node/app/setup.sh
