version: '3'

services:
  db:
    image: docker.pkg.github.com/helloworlddevs/bentericksen/bentericksen-mysql:latest
    container_name: hrdirector-e2e-db
    env_file: [laravel/.env.testing.example]
    working_dir: /workspace
    ports:
      - "4306:3306"
    volumes:
      - ./data-e2e:/var/lib/mysql
      - ./docker/mysql/hrdirector.cnf:/etc/mysql/conf.d/hrdirector.cnf
  php:
    image: docker.pkg.github.com/helloworlddevs/bentericksen/bentericksen-php:3.0
    container_name: hrdirector-e2e-php
    depends_on:
      - db
    working_dir: /code/laravel
    command: "./run.sh"
    volumes:
      - ./httpdocs:/code/httpdocs
      - ./laravel:/code/laravel
      - ./laravel/.env.testing.example:/code/laravel/.env
      - ./docker/php/run.sh:/code/laravel/run.sh
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/test-setup.sh:/code/laravel/test-setup.sh
      - ./docker/php/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    env_file: [laravel/.env.testing.example]
  web:
    image: nginx:latest
    container_name: hrdirector-e2e-web
    depends_on:
      - php
    volumes:
      - ./httpdocs:/code/httpdocs
      - ./laravel:/code/laravel
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx-selfsigned-hrdirector.key:/etc/nginx/conf.d/nginx-selfsigned-hrdirector.key
      - ./docker/nginx/nginx-selfsigned-hrdirector.crt:/etc/nginx/conf.d/nginx-selfsigned-hrdirector.crt
    ports:
      - "80:80"
