name: CI Testing

on:
  pull_request:
    branches:
      - dev
      - staging
      - prod

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build the unit testing stack
      run: docker-compose -f docker-compose.testing.yml build
    - name: Install PHP Dependencies
      run: docker-compose -f docker-compose.testing.yml run --rm php composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Prep unit testing environment (PHP)
      run: docker-compose -f docker-compose.testing.yml run --rm php ./test-setup.sh
    - name: Run test suite (PHP)
      run: docker-compose -f docker-compose.testing.yml run --rm php
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Run test suite (Node)
      run: cd laravel && yarn install && yarn test
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: genereate ssl keys
      run: openssl req -config docker/nginx/openssl.cnf -new -sha256 -newkey rsa:2048 -nodes -keyout docker/nginx/nginx-selfsigned-hrdirector.key -x509 -days 825 -out docker/nginx/nginx-selfsigned-hrdirector.crt
    - name: Build the e2e testing stack
      run: docker-compose -f docker-compose.e2e.yml build
    - name: Install PHP Dependencies
      run: |
        docker-compose -f docker-compose.e2e.yml run --rm php composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        docker-compose -f docker-compose.e2e.yml run --rm php composer require caxy/php-htmldiff

    - name: Prep e2e testing environment
      run: docker-compose -f docker-compose.e2e.yml run --rm php ./test-setup.sh
    - name: Install And Build Frontend
      run: docker-compose -f docker-compose.e2e.yml run --rm node ./yarn-install.sh
    - name: Run e2e Tests
      run: ./test-e2e-all.sh $BROWSER_STACK_USER $BROWSER_STACK_KEY
      env:
        BROWSER_STACK_KEY: ${{secrets.BROWSER_STACK_KEY}}
        BROWSER_STACK_USER: ${{secrets.BROWSER_STACK_USER}}